version: "3.8"
services:
  postgres:
    build: 
      context: .
      dockerfile: postgres/Dockerfile
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d/
    ports:
      - 5431:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}