version: "3.9"

services:
  jenkins_docker:
    container_name: jenkins-docker
    image: jenkins
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home