pipeline {
	agent any
    environment {
        NEW_VERSION = '0.0.1'
    }
	stages {
        stage("init") {
            steps {
                script {
                    gv = load "DE/jenkins/crawling.groovy"
                }
            }
        }
		stage("crawling") {
            // when {
            //     expression {
            //         env.GIT_BRANCH == 'origin/jenkins'
            //     }
            // }
			steps {
                echo "webhook2"
                script {
                    gv.crawlingApp()
                }
			}
		}
	}
    post {
        always {
            echo 'building..'
        }
        success {
            echo 'success'
        }
        failure {
            echo 'failure'
        }
    }
}